### PR TITLE
Fix Unlock Vents

### PR DESCRIPTION
**Pull request by manianac**
This branch will be for fixing vent related abilities

Currently the unlock vents feature now works for Engineer and other classes.  Will need to fix the cooldown display on the Engineer Ability button after

### CODE REVIEW

**Review by v0idp — DISMISSED** [review]

**Comment by v0idp** [comment]
any plans on fixing the cooldown on engineer or want me to merge this already ?

**Comment by manianac** [comment]
> any plans on fixing the cooldown on engineer or want me to merge this already ?

I'm still determining how easy it would be first.  I would leave this as a draft, and add any further changes if you see them

**Comment by StupidRepo** [comment]
On the topic of vents, can we make it possible to shapeshift in vents? In free play (where I can’t get banned for Shifting) if you shapeshift and enter a vent and wait for the timer to run out on the disguise or just even click Unshift, the shapeshift animations plays above the vent you’re in and doesn’t push you out of vent. You can open the shapeshift menu in vents but cannot shape shift. Maybe try making this possible?

**Comment by manianac** [comment]
Alright, ready for review if you guys can test if I missed anything.

**Comment by StupidRepo** [comment]
Pull this request!

**Comment by manianac** [comment]
> On the topic of vents, can we make it possible to shapeshift in vents? In free play (where I can’t get banned for Shifting) if you shapeshift and enter a vent and wait for the timer to run out on the disguise or just even click Unshift, the shapeshift animations plays above the vent you’re in and doesn’t push you out of vent. You can open the shapeshift menu in vents but cannot shape shift. Maybe try making this possible?

Not at this time, we haven't implemented overriding abilities yet

**Review by v0idp — APPROVED** [review]

**Pull request merged**
