### PR TITLE
Added sliders to settings.json

### PR DESCRIPTION
**Pull request by DarkReaper231**
They don't have any reason to not exist so they might as well just do

### CODE REVIEW

**Comment by v0idp** [comment]
You forgot to actually save them into the settings.json. You only try to read from it.

**Comment by DarkReaper231** [comment]
> You forgot to actually save them into the settings.json. You only try to read from it.

Oh I did notice that I have to write them manually but I didn't find the code where they are written into the file.

**Review by kotae4 — APPROVED** [review]

**Comment by kotae4** [comment]
Ah, you need to sign your commits before merging is allowed.

**Comment by DarkReaper231** [comment]
> Ah, you need to sign your commits before merging is allowed.

Damn I did the first commit in CLI and I don't know how to sign in CLI

**Comment by DarkReaper231** [comment]
> Check this for a guide on how to sign previous commits: https://hyperledger-indy.readthedocs.io/projects/sdk/en/latest/docs/contributors/signing-commits.html

I'll just open new PR, I am lost

**Pull request closed without merging**
