### PR TITLE
[BugFix] #544 Fix HidenSeek role issues (Still not fully fixed)

### LINKED ISSUE #544: [Bug] Using Aum as host causes all crews in hide n seek to be crewmates
QQ截图20230627181841
QQ截图20230627181910
QQ截图20230627181918

Repeated the issue in huge rooms.
You can avoid this by settings others to engineer in host tab.

### PR DESCRIPTION
**Pull request by hs233666**
Fix #544

### CODE REVIEW

**Review by v0idp — APPROVED** [review]

**Comment by OsOmE1** [comment]
can we test this first before it gets merged

**Comment by GDjkhp** [comment]
> can we test this first before it gets merged

tried it on my fork. works flawlessly.

**Comment by hs233666** [comment]
Wait why is it not pushed

**Comment by hs233666** [comment]
Not completely fixed.
1.Need to check assigned roles to prevent AUM from assigning another role in hidenseek(If host assigned a imp)
2.Conflict with lobby assign imp. (Ignore lobby settings)
Still need improvement

**Pull request closed without merging**
