### PR TITLE
#260: Reveal Votes

### LINKED ISSUE #260: Live vote count on voting screen
This is a feature request. On the voting screen there would be a number next to each player showing how many votes they have currently received (Also skip button needs a number too). This can sometimes help you vote for someone (or skip) so that it leads to a tie on purpose.

### PR DESCRIPTION
**Pull request by cddjr**
closes #260

### CODE REVIEW

**Comment by cddjr** [comment]
rv

**Comment by v0idp** [comment]
I see you took that function I mentioned in the issue. Is this finished or still WIP ?

**Comment by cddjr** [comment]
> I see you took that function I mentioned in the issue. Is this finished or still WIP ?

I have finished.

**Review by DarkPenguin24 — CHANGES_REQUESTED** [review]
There is one issue with this logic:
If someone votes while RevealVotes is disabled and u enable it at a later point u won't see the votes that were made already and they will also not appear at the end of the meeting which leads into false behaviour (e.g. only 2 people voting on person A which gets ejected while 4 people voted on person B).

**Comment by v0idp** [comment]
> There is one issue with this logic: If someone votes while RevealVotes is disabled and u enable it at a later point u won't see the votes that were made already and they will also not appear at the end of the meeting which leads into false behaviour (e.g. only 2 people voting on person A which gets ejected while 4 people voted on person B).

maybe adding a second check on the hooked blipvote function and if that person didn't vote yet execute the original function

**Comment by DarkPenguin24** [comment]
this will fix it for "end of meeting". would prefer to fix it in a way it is always visible or not (depending on the state of RevealVotes. Like it is for the roles.

**Comment by v0idp** [comment]
wouldn't that mean that if it's disabled it wouldn't show at all anymore ? that's what I get from what you're saying. or do you mean also remove the previously drawn ones ?

**Comment by puscher** [comment]
Ideally:
Enabled -> show all votes that were made and all votes that will come in
Disabled -> show nothing at all (remove already drawn icons)

Same behaviour as we have for Roles:
Enabled -> shown
Disabled -> not shown at all (except of Red if you are imposter)

**Comment by cddjr** [comment]
> Ideally: Enabled -> show all votes that were made and all votes that will come in Disabled -> show nothing at all (remove already drawn icons)
> 
> Same behaviour as we have for Roles: Enabled -> shown Disabled -> not shown at all (except of Red if you are imposter)

I have changed the code, please review.

**Review by DarkPenguin24 — APPROVED** [review]

**Pull request merged**
