### PR TITLE
Update to v2022.12.08e

### LINKED ISSUE #462: Update to 2022.12.8s
I know devs know. Figured id post for others & also maybe close when updated lol

### PR DESCRIPTION
**Pull request by cddjr**
Based on v2022.12.08e(2603)

closes #462

### CODE REVIEW

**Comment by Xtendera** [comment]
> Based on v2022.12.08e(2603)
> 
> closes #462

Yo, I have two questions. If u can answer that would be awesome.

1) What mod of il2cppinspector do u use.
2) How do u compile it? (I get different errors in both VS2019 and 2022)

**Comment by william1east** [comment]
Do you wants someone to approve so that we can merge or no?

**Review by william1east — APPROVED** [review]
Im a idiot that did not help in the slightest
Please dismiss this review so i dont have to see it anymore

**Comment by v0idp** [comment]
> Do you wants someone to approve so that we can merge or no? I'd love to see this change being made
> I'll take that thumbs up as a yes

Approving code changes only works with team members. If you do it nothing will happen.

**Comment by william1east** [comment]
> > Do you wants someone to approve so that we can merge or no? I'd love to see this change being made
> > I'll take that thumbs up as a yes
> 
> Approving code changes only works with team members. If you do it nothing will happen.

oof im an idiot

**Review by FrostX-Official — DISMISSED** [review]

**Review by manianac — APPROVED** [review]
Excellent work!

**Comment by OsOmE1** [comment]
Thank again @cddjr!

**Pull request merged**
