### PR TITLE
Update to 2022.8.24

### PR DESCRIPTION
**Pull request by cddjr**
Based on v2022.8.24e(2267)

### CODE REVIEW

**Review by AAAAAXfda — APPROVED** [review]
Looks good.

**Comment by AAAAAXfda** [comment]
I'll get back to you, I'm currently compiling and going to be testing the PR.

**Review by AAAAAXfda — APPROVED** [review]
**@cddjr @ChaseBrand @v0idp @OsOmE1 @kotae4 @std-nullptr** 
**Upon further review, it's safe to say that cddjr's patch is working flawlessly. I'll be merging this to the main branch in a moment.**
Among_Us_5Lc4eDtyRv

**Comment by ChaseBrand** [comment]
Pretty sure merging is blocked until a core team member reviews it. If no one beats me to it, I'll do it after work.

**Comment by OsOmE1** [comment]
> **@cddjr @ChaseBrand @v0idp @OsOmE1 @kotae4 @std-nullptr** **Upon further review, it's safe to say that cddjr's patch is working flawlessly. I'll be merging this to the main branch in a moment.** Among_Us_5Lc4eDtyRv

Okay yes pls merge into main 👍

**Comment by OsOmE1** [comment]
On a more serious note looks good and works for what I tested thanks again @cddjr for the great work on the update.

**Review by OsOmE1 — APPROVED** [review]

**Pull request merged**
