### PR TITLE
#321: Fix report/meeting event missing

### LINKED ISSUE #321: Some events are not registered/registered improperly
(mostly report and meeting events)

### PR DESCRIPTION
**Pull request by cddjr**
In some cases, 'PlayerControl_ReportDeadBody' will not be triggered. 
So I changed to hook the 'PlayerControl_CoStartMeeting' function to make sure the event is logged.

fixes #321

### CODE REVIEW

**Comment by cddjr** [comment]
无标题

**Comment by v0idp** [comment]
According to your graph it will only trigger when you're host, what about games where you are not the host ?

**Comment by cddjr** [comment]
> According to your graph it will only trigger when you're host, what about games where you are not the host ?

Players will receive RpcCalls::StartMeeting from host.

**Comment by v0idp** [comment]
> > According to your graph it will only trigger when you're host, what about games where you are not the host ?
> 
> Players will receive RpcCalls::StartMeeting from host.

you mean the CoStartMeeting you hook too?

**Comment by cddjr** [comment]
> 

Yes, just hook it.

> > > According to your graph it will only trigger when you're host, what about games where you are not the host ?
> > 
> > 
> > Players will receive RpcCalls::StartMeeting from host.
> 
> you mean the CoStartMeeting you hook too?

Yes, it’s always triggered by meetings. So we don’t need to hook CmdReportDeadBody and ReportDeadBody.

**Review by v0idp — APPROVED** [review]

**Pull request merged**
