### PR TITLE
Update to 2023.10.24

### LINKED ISSUE #603: update
Do you have any plans for updating the menu?

### LINKED ISSUE #604: Update for v2023.10.24
Can the team update the v2023.10.24? new cosmetics have been added

### PR DESCRIPTION
**Pull request by cddjr**
closes #604
closes #603

### CODE REVIEW

**Review by kotae4 — DISMISSED** [review]
In hooks/PlainDoor.cpp the new usage of get_class can be expensive. Might cause a slow frame when these functions run on potato PCs. Might be worth saving the class variable elsewhere, or wrapping it in an `if (klassPlainDoor == NULL) { // get_class }` block. A micro-optimization either way.

Great work. Super fast.

**Comment by onesailant** [comment]
how can i download this files?

**Comment by onesailant** [comment]
can some help me to install this mode? my discord xxxxxxxxxx2222

**Comment by qLeooo** [comment]
> how can i download this files?

https://github.com/cddjr/AmongUsMenu/tree/2023.10.24

**Comment by PokeSaibott** [comment]
i build the debug version and when i try to inject i got this error                                                                                                                   

Unable to locate PlayerControl_MurderPlayer
Unable to locate PlayerControl_RpcMurderPlayer
Unable to locate ShipStatus_RpcRepairSystem
Unable to locate ShipStatus_RepairSystem
Unable to locate Vent_ExitVent
Unable to locate PlayerControl_TurnOnProtection
Unable to locate SabotageSystemType_ForceSabTime
[16:15:05][DEBUG - AUM - cctor_finished] Class AmongUsClient Has Static Constructor: false
[16:15:05][DEBUG - AUM - Run] Game::pAmongUsClient is 0x21E67D40 -> 0x2251EB60
[16:15:05][DEBUG - AUM - cctor_finished] Class GameData Has Static Constructor: true
[16:15:05][DEBUG - AUM - Run] Game::pGameData is 0x21E67ED0 -> 0x00000000
[16:15:05][DEBUG - AUM - cctor_finished] Class PlayerControl Has Static Constructor: true
[16:15:05][DEBUG - AUM - Run] Game::pAllPlayerControls is 0x21E67F24 -> 0x22508480
[16:15:05][DEBUG - AUM - cctor_finished] Class PlayerControl Has Static Constructor: true
[16:15:05][DEBUG - AUM - Run] Game::pLocalPlayer is 0x21E67F20 -> 0x00000000
[16:15:05][DEBUG - AUM - cctor_finished] Class ShipStatus Has Static Constructor: false
[16:15:05][DEBUG - AUM - Run] Game::pShipStatus is 0x1CDD4530 -> 0x00000000
[16:15:05][DEBUG - AUM - cctor_finished] Class LobbyBehaviour Has Static Constructor: false
[16:15:05][DEBUG - AUM - Run] Game::pLobbyBehaviour is 0x1CDD4538 -> 0x00000000
[16:15:05][DEBUG - AUM - Run] Game::RoleManager is 0x1fe5cca8
Failed to hook Vent_ExitVent, error 6

**Review by kotae4 — APPROVED** [review]

**Pull request merged**
