### PR TITLE
[Replay] #359: Fix Showing dead players in whole timeline

### LINKED ISSUE #359: Replay Showing Dead Player in whole Timeline
Player Icons on Replay Map will show as dead if they died no matter which timestamp.
this needs to be fixed so the dead icon only starts from the timestamp where the player died.

### PR DESCRIPTION
**Pull request by cddjr**
babe39d fixes #359.
0464fe9 fixed a crash reported by dreeeee.
5397c5e fixed a meeting freeze issue.

### CODE REVIEW

**Comment by cddjr** [comment]
work done, please check out for errors.

**Comment by v0idp** [comment]
> work done, please check out for errors.

please answer to my review

**Comment by manianac** [comment]
@cddjr, why did you copy the flipskeld code from ShipStatus?

https://github.com/BitCrackers/AmongUsMenu/pull/367/files#diff-c577b553fed30edb64e77354aa77f10edd7abc3c1bda36c7559ed0d276b0920cR13-R16

**Comment by cddjr** [comment]
> @cddjr, why did you copy the flipskeld code from ShipStatus?
> 
> https://github.com/BitCrackers/AmongUsMenu/pull/367/files#diff-c577b553fed30edb64e77354aa77f10edd7abc3c1bda36c7559ed0d276b0920cR13-R16

I see this code in both PolusShipStatus and ShipStatus. I will delete it if not necessary

**Comment by manianac** [comment]
Yea, I think it was accidentally copy/pasted.  Please remove it from everything except `ShipStatus`.  Thank you!

**Review by v0idp — APPROVED** [review]

**Pull request merged**
