### PR TITLE
Fix Vent Unlocking

### PR DESCRIPTION
**Pull request by manianac**
Sorry @kotae4, I went back to the old types.h for now.  This PR will fix both shapeshifter vent unlocking and engineer.  Unlocking as engineer disables cooldown/invent timers.

### CODE REVIEW

**Comment by manianac** [comment]
This fixes #261

**Review by v0idp — CHANGES_REQUESTED** [review]
Will merge it when we have a slimmed down version of types.h
I highly recommend writing a little script to generate our own types.h based on the used_types.txt

**Comment by v0idp** [comment]
any updates on this @kotae4 @manianac

**Comment by manianac** [comment]
Nothing yet, need to implement the class checks and the trimmed types.h

**Pull request closed without merging**
