### PR TITLE
Create Kepsamongus

### PR DESCRIPTION
**Pull request by KeplerBB**
......

### CODE REVIEW

**Review by AAAAAXfda — COMMENTED** [review]
Need more info...

**Comment by Xanthus58** [comment]
> Need more info...

@AAAAAXfda I believe this type of commit is very common for projects that have auto-merge if no conflicts. I've seen this before and i believe the entire reason for the commit is to just become apart of the "contributors" section. I've heard people do this for clout; or for "experience" on their resume or portfolio.

**Comment by AAAAAXfda** [comment]
@Xanthus58 It doesn't have auto-merge...

**Comment by Xanthus58** [comment]
> @Xanthus58 It doesn't have auto-merge...

I'm aware of that I just thought I'd share my experiences with this in other projects.And possibly give you some insight you may not have otherwise had.

**Comment by AAAAAXfda** [comment]
> > @Xanthus58 It doesn't have auto-merge...
> 
> I'm aware of that I just thought I'd share my experiences with this in other projects.And possibly give you some insight you may not have otherwise had.

Ok.

**Review by AAAAAXfda — APPROVED** [review]
Upon further review, Kepler's patch for v2022.8.24 has been tested and is looking good so far. Approving and merging this.

**Review by AAAAAXfda — APPROVED** [review]

**Comment by AAAAAXfda** [comment]
@Xanthus58 Why is it not merging

**Comment by Xanthus58** [comment]
> @Xanthus58 Why is it not merging

Not sure but guven that the only change is adding an empty file. I don't see the point ik merging the commit as it's an empty pr I can check when I get back toy PC in 10 mins or so if you'd like.

**Comment by Xanthus58** [comment]
Alrighty I'm back sorry for the wait.  The reason its not merging is because the commit needs to be maintainer approved not reviewer approves. (This is because its his first ever commit)

In regards to the empty commit i was explaining earlier you can see exactly whats changed here. https://github.com/BitCrackers/AmongUsMenu/pull/410/files And if you notice its only a singular new empty file.

@AAAAAXfda

**Comment by AAAAAXfda** [comment]
**@Xanthus58** 
**It's not empty. I've complied Kepler's AUM patch and it seems to be working for the latest Among Us update.
One slight issue though, you get a 3 fps drop, other than that it's looking good.
https://github.com/KeplerBB/AmongUsMenu/tree/patch-1, I believe this is why you get a slight fps drop):
image**

**Comment by ChaseBrand** [comment]
The PR is empty outside of a single file that contains "+". I will not be approving this.

**Pull request closed without merging**
